In [1]:
# Алексеев Д.П. (DSU-4,MDS-18)
# Домашнее задание к лекции «Основные математические понятия» (#1)

# 1) Даны векторы x = (1,1), y = (2, 0) и z = (0,2)
# Необходимо в Python:
# ● Изобразить векторы на экране
# ● Изобразить точку x + y + z
# ● Найти угол между векторами x и y

# 2) Необходимо в Python:
# ● Создайте матрицу 3 на 3, заполненную числами от 1 до 9
# ● Прибавьте к ней матрицу с единицами на диагонали
# ● Умножьте полученную матрицу на вектор (1, 2, 3)

# 3) Необходимо в Python:
# f(x) = 3x(x^2+x)^3  
# примечание: формула f(x) в презентации отличается от формулы f(x) в вебинаре (в вебинаре: f(x) = (x^2+x)^3)

# Посчитайте значение первой и второй производной функции
# В точке x = 1


In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:
# 1) Даны векторы x = (1,1), y = (2, 0) и z = (0,2)
# Необходимо в Python:
# ● Изобразить векторы на экране

# зададим векторы x = (1,1), y = (2, 0) и z = (0,2)
x = np.array([1, 1])
y = np.array([2, 0])
z = np.array([0, 2])

# ● Изобразить точку x + y + z
# посчитаем сперва сумму векторов
sum_ = x + y + z

In [13]:
# отобразим исходные векторы и сумму на одной плоскости
plt.figure()
plt.plot(x[0], x[1], 'b+') #синий плюс
plt.plot(y[0], y[1], 'r*') #красная звездочка
plt.plot(z[0], z[1], 'go') #зеленая точка
plt.plot(sum_[0], sum_[1], 'ro') #красная точка
plt.grid()
plt.show()

In [17]:
# ● Найти угол между векторами x и y
np.rad2deg(np.arccos(np.dot(x, y)/(np.linalg.norm(x)*np.linalg.norm(y))))
# ответ: угол между векторами x и y равен 45 градусов.

45.00000000000001

In [19]:
# 2) Необходимо в Python:
# ● Создайте матрицу 3 на 3, заполненную числами от 1 до 9
A1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# ● Прибавьте к ней матрицу с единицами на диагонали
# сперва создадим матрицу с единицами на диагонали
A2 = np.array([[1,0,0], [0,1,0], [0,0,1]])
A2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
summ_A = A1 + A2
summ_A

array([[ 2,  2,  3],
       [ 4,  6,  6],
       [ 7,  8, 10]])

In [26]:
# ● Умножьте полученную матрицу на вектор (1, 2, 3)
# сперва создадим вектор (1, 2, 3)
x1 = np.array([1, 2, 3])
x1

array([1, 2, 3])

In [27]:
# обычное(поэлементное) перемножение матрицы на вектор:
summ_A * x1

array([[ 2,  4,  9],
       [ 4, 12, 18],
       [ 7, 16, 30]])

In [28]:
# перемножение матрицы на вектор на основе скалярных произведений:
summ_A @ x1

array([15, 34, 53])

In [35]:
# 3) Необходимо в Python:
# f (x) = 3x(x^2+x)^3
#примечание: формула f(x) в презентации отличается от формулы f(x) в вебинаре (в вебинаре: f(x) = (x^2+x)^3)

# Посчитайте значение первой и второй производной функции
# В точке x = 1
import sympy as sym

In [39]:
# выведем формулу функции f(x) на экран в привычном виде
x = sym.Symbol('x')
3*x*(x**2+x)**3

3*x*(x**2 + x)**3

In [41]:
# вычислим формулу первой производной
diff1 = sym.diff(3*x*(x**2+x)**3, x, 1)
diff1

3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3

In [42]:
# рассчитаем значение первой производной в точке x = 1
diff1.subs(x, 1)

132

In [43]:
# вычислим формулу второй производной
diff2 = sym.diff(3*x*(x**2+x)**3, x, 2)
diff2

18*x**2*(x + 1)*(x*(x + 1) + (x + 1)*(2*x + 1) + (2*x + 1)**2)

In [44]:
# рассчитаем значение второй производной в точке x = 1
diff2.subs(x, 1)

612