In [ ]:
# Алексеев Д.П. (DSU-4,MDS-18)
# Домашнее задание к лекции «Линейная алгебра. Матрицы» (#2)

# 1) Создайте случайную матрицу А1 размерностью 5 на 5
# 2) Транспонируйте матрицу A1
# 3) Найдите обратную матрицу для А1
# 4) Создайте диагональную матрицу - поэлементно перемножив единичную
# матрицу I и случайную матрицу A2 размерности 4 на 4
# 5) Создайте нулевую матрицу размерности 3 на 3
# 6) Для всех полученных матриц найдите: определитель, ранг и собственные
# значения
# 7) Проанализируйте результаты

In [1]:
import numpy as np

In [2]:
# 1) Создайте случайную матрицу А1 размерностью 5 на 5
#зафиксируем состояние генератора случайных чисел, чтобы не пересчитывать каждый раз заново последующие пункты
A1 = np.random.RandomState(seed=42).random((5,5)) 
A1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

In [10]:
# 2) Транспонируйте матрицу A1
A1_trans = np.transpose(A1)
A1_trans

array([[0.37454012, 0.15599452, 0.02058449, 0.18340451, 0.61185289],
       [0.95071431, 0.05808361, 0.96990985, 0.30424224, 0.13949386],
       [0.73199394, 0.86617615, 0.83244264, 0.52475643, 0.29214465],
       [0.59865848, 0.60111501, 0.21233911, 0.43194502, 0.36636184],
       [0.15601864, 0.70807258, 0.18182497, 0.29122914, 0.45606998]])

In [9]:
# 3) Найдите обратную матрицу для А1
A1_inv = np.linalg.inv(A1)
A1_inv

array([[  364.60350483,   334.16789204,   -91.41631021,  -895.54602541,
          -35.23406016],
       [ -351.86538626,  -323.93604372,    89.07808984,   864.20754679,
           35.93471989],
       [  584.80763977,   538.00659297,  -146.16417479, -1436.8998493 ,
          -59.51982157],
       [ -234.80558669,  -217.08098236,    57.15090649,   582.66687482,
           22.50116178],
       [ -567.51216365,  -519.48181002,   143.11544206,  1389.49392418,
           58.52220068]])

In [5]:
# 4) Создайте диагональную матрицу - поэлементно перемножив единичную
# матрицу I и случайную матрицу A2 размерности 4 на 4

A2 = np.random.RandomState(seed=20).random((4,4)) 
A2

array([[0.5881308 , 0.89771373, 0.89153073, 0.81583748],
       [0.03588959, 0.69175758, 0.37868094, 0.51851095],
       [0.65795147, 0.19385022, 0.2723164 , 0.71860593],
       [0.78300361, 0.85032764, 0.77524489, 0.03666431]])

In [6]:
# создадим единичную матрицу
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
# создадим диагональную матрицу поэлементным перемножением
Diag = I * A2
Diag

array([[0.5881308 , 0.        , 0.        , 0.        ],
       [0.        , 0.69175758, 0.        , 0.        ],
       [0.        , 0.        , 0.2723164 , 0.        ],
       [0.        , 0.        , 0.        , 0.03666431]])

In [16]:
# 5) Создайте нулевую матрицу размерности 3 на 3
Null_ = np.zeros([3,3])
Null_

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 6) Для всех полученных матриц найдите: определитель, ранг и собственные
# значения.
# 7) Проанализируйте результаты.

In [11]:
# а) ранг:
np.linalg.matrix_rank(A1)
# ранг равен 5, т.к. это матрица случайных чисел, все векторы(строки) в ней уникальны

5

In [12]:
np.linalg.matrix_rank(A1_trans)
# ранг равен 5, т.к. это транспонированная матрица случайных чисел, все векторы(строки) в ней уникальны

5

In [13]:
np.linalg.matrix_rank(A1_inv)
# ранг равен 5, т.к. это обратная матрица к матрице из случайных чисел, все векторы(строки) в ней уникальны

5

In [19]:
np.linalg.matrix_rank(A2)
# ранг равен 4, т.к. это матрица случайных чисел размером 4х4, все векторы(строки) в ней уникальны

4

In [18]:
np.linalg.matrix_rank(I)
# ранг равен 4, т.к. это единичная матрица, все векторы(строки) в ней уникальны

4

In [14]:
np.linalg.matrix_rank(Diag)
# ранг равен 4, т.к. это диагональная матрица, полученная перемножением матрицы случайных чисел размером 4х4 на единичную.
# Все векторы(строки) в ней уникальны

4

In [17]:
np.linalg.matrix_rank(Null_)
# ранг равен 0, т.к. ранг нулевой матрицы любого размера равен нулю.

0

In [20]:
# б) определитель:
np.linalg.det(A1)
# определитель случайной матрицы (не совсем понятно, что именно анализировать)

-0.0001034597121343134

In [21]:
np.linalg.det(A1_trans)
# определитель транспонированной матрицы A1_trans равен определителю исходной матрицы A1

-0.00010345971213430477

In [22]:
np.linalg.det(A1_inv)
# определитель матрицы A1_inv, обратной от A1, равен (1 / определитель матрицы A1), 
# т.е. (1 / -0.0001034597121343134) = -9665.59812868835

-9665.59812868835

In [23]:
np.linalg.det(A2)
# определитель случайной матрицы (не совсем понятно, что именно анализировать)

0.1287360122879459

In [24]:
np.linalg.det(I)
# определитель единичной матрицы равен единице

1.0

In [25]:
np.linalg.det(Diag)
# определитель случайной диагональной матрицы (не совсем понятно, что именно анализировать)

0.004062048706093961

In [26]:
np.linalg.det(Null_)
# определитель нулевой матрицы равен нулю

0.0

In [29]:
# в) собственные значения:
np.linalg.eigvals(A1)
# собственные значения случайной матрицы A1 (не совсем понятно, что именно анализировать)

array([ 2.16629999e+00+0.j        , -3.34610340e-01+0.j        ,
        1.59759579e-01+0.22516272j,  1.59759579e-01-0.22516272j,
        1.87256342e-03+0.j        ])

In [30]:
np.linalg.eigvals(A1_trans)
# так как определители матрицы A1 и её транспонированной матрицы A1_trans равны, 
# то и собственные числа матриц также равны

array([ 2.16629999e+00+0.j        , -3.34610340e-01+0.j        ,
        1.59759579e-01+0.22516272j,  1.59759579e-01-0.22516272j,
        1.87256342e-03+0.j        ])

In [31]:
np.linalg.eigvals(A1_inv)
# собственные значения матрицы A1_inv, обратной к случайной матрице A1 (не совсем понятно, что именно анализировать)

array([ 5.34027307e+02+0.j        ,  2.09599447e+00+2.95406274j,
        2.09599447e+00-2.95406274j, -2.98855080e+00+0.j        ,
        4.61616582e-01+0.j        ])

In [32]:
np.linalg.eigvals(A2)
# собственные значения случайной матрицы A2 (не совсем понятно, что именно анализировать)

array([ 2.21872814,  0.31815201, -0.26831661, -0.67969445])

In [33]:
np.linalg.eigvals(I)
# собственные значения единичной матрицы представляют собой единичный вектор

array([1., 1., 1., 1.])

In [34]:
np.linalg.eigvals(Diag)
# собственные значения случайной диагональной матрицы Diag (не совсем понятно, что именно анализировать)

array([0.5881308 , 0.69175758, 0.2723164 , 0.03666431])

In [35]:
np.linalg.eigvals(Null_)
# собственные значения нулевой матрицы представляют собой нулевой вектор

array([0., 0., 0.])